@CodeMind.Api_HostAddress = http://localhost:5083

GET {{CodeMind.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

# Kafka Test Mesajı Gönder
POST {{CodeMind.Api_HostAddress}}/api/test/send-kafka-message
Accept: application/json

###
